[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.build]
cmds = ["npm install --production"]

[start]
cmd = "node server-simple.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
ADMIN_EMAIL = "admin@eldorethama.com"
ADMIN_PASSWORD = "admin123"